import { createCorpusClient, type CorpusClient } from "@corpus/contract/client";

/**
 * The UI always talks to its own origin: in development the Vite dev server
 * proxies `/api` and `/events` to `127.0.0.1:8765`, and in the installed tool
 * the server serves the built UI itself (SPEC.md §3). So there is no base URL
 * to configure — only a base URL to inherit.
 */
function currentOrigin(): string {
  return globalThis.location.origin;
}

/**
 * Token provisioning is not solved yet. SPEC.md §2.1 gives the workspace a
 * bearer token generated by `corpus init`; handing it to the browser is the
 * job of the server that serves the UI (SERVER-003). Until then the UI issues
 * exactly one request — `GET /api/health` — which the contract declares
 * unauthenticated for precisely this kind of probe. Every authenticated query
 * arrives with UI-002, by which time the server can inject a real token.
 */
const UNPROVISIONED_TOKEN = "";

export interface UiClientOptions {
  readonly baseUrl?: string;
  readonly token?: string;
  readonly fetch?: typeof globalThis.fetch;
}

export function createUiClient(options: UiClientOptions = {}): CorpusClient {
  return createCorpusClient({
    baseUrl: options.baseUrl ?? currentOrigin(),
    token: options.token ?? UNPROVISIONED_TOKEN,
    // Late-bound on purpose: `openapi-fetch` captures the transport when the
    // client is built, and this client is built at module load.
    fetch: options.fetch ?? ((input, init) => globalThis.fetch(input, init)),
  });
}

export const uiClient: CorpusClient = createUiClient();
