import { commandSynopsis, flagUsage } from "../help.js";
import { GLOBAL_FLAGS } from "../registry/globals.js";
import type { ArgSpec, CommandSpec, FlagSpec, Registry } from "../registry/types.js";
import { validateRegistry } from "../registry/validate.js";
import { EXIT_CODES } from "../errors.js";

/**
 * The registry rendered as the committed CLI reference — the mirror of the
 * contract's `openapi.json` (SPEC.md §2.3, §9.3). Output is a pure function of
 * the registry: topics and commands are sorted by name and nothing carries a
 * timestamp, so regenerating is a no-op unless the surface actually changed.
 */

export const CLI_DOCS_RELATIVE_PATH = "docs/cli.md";

export const DOCS_HEADER =
  "<!-- Generated by `npm run docs:cli -w apps/cli` — do not edit by hand. -->";

export function generateCliDocs(registry: Registry): string {
  validateRegistry(registry);

  const commands = [...registry.commands].sort(byName);
  const topics = [...registry.topics].sort(byName);

  const lines: string[] = [
    DOCS_HEADER,
    "",
    "# `corpus` command reference",
    "",
    `\`corpus\` — ${registry.summary}`,
    "",
    "Every command below is declared once in the CLI's command registry",
    "(`apps/cli/src/registry/`). That single declaration drives the dispatcher, every level of",
    "`--help`, and this file, so behaviour, help and documentation cannot disagree. This file is",
    "regenerated with `npm run docs:cli -w apps/cli` and a stale copy fails pre-push and CI.",
    "",
    "## Contents",
    "",
    "- [Usage](#usage)",
    "- [Global flags](#global-flags)",
  ];

  for (const command of commands) {
    const path = `corpus ${command.name}`;
    lines.push(`- [\`${path}\`](#${anchor(path)})`);
  }
  for (const topic of topics) {
    lines.push(`- [\`corpus ${topic.name}\`](#${anchor(`corpus ${topic.name}`)})`);
    for (const command of [...topic.commands].sort(byName)) {
      const path = `corpus ${topic.name} ${command.name}`;
      lines.push(`  - [\`${path}\`](#${anchor(path)})`);
    }
  }
  lines.push("- [Exit codes](#exit-codes)", "");

  lines.push(
    "## Usage",
    "",
    "```",
    "corpus <command> [args] [flags]",
    "corpus <topic> <verb> [args] [flags]",
    "```",
    "",
    "Three levels of help are rendered from the registry: `corpus --help` lists topics and",
    "commands, `corpus <topic> --help` lists that topic's verbs, and",
    "`corpus <topic> <verb> --help` shows arguments, flags and examples. Running `corpus` with",
    "no arguments prints the top-level help and exits `0`.",
    "",
    "`--help` is a deliberate exception to `--json`: combining them still prints human-readable",
    "help, because help is documentation rather than data.",
    "",
    "## Global flags",
    "",
    "These are merged into every command; a command may not declare a flag that shadows one.",
    "",
    ...flagTable(GLOBAL_FLAGS),
    "",
  );

  for (const command of commands) {
    lines.push(...commandSection(command, undefined));
  }
  for (const topic of topics) {
    lines.push(`## \`corpus ${topic.name}\``, "", topic.summary, "");
    if (topic.description !== undefined) lines.push(topic.description, "");
    for (const command of [...topic.commands].sort(byName)) {
      lines.push(...commandSection(command, topic.name));
    }
  }

  lines.push("## Exit codes", "", ...exitCodeTable(), "");

  return `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

function byName(a: { readonly name: string }, b: { readonly name: string }): number {
  return a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
}

function commandSection(command: CommandSpec, topic: string | undefined): readonly string[] {
  const path = topic === undefined ? `corpus ${command.name}` : `corpus ${topic} ${command.name}`;
  const heading = topic === undefined ? "##" : "###";
  const lines: string[] = [`${heading} \`${path}\``, "", command.summary, ""];

  if (command.description !== undefined) lines.push(command.description, "");
  lines.push("```", commandSynopsis(command, topic), "```", "");

  if (command.requiresWorkspace === false) {
    lines.push("Runs outside a workspace; it does not contact the server.", "");
  }

  if (command.args.length > 0) {
    lines.push("**Arguments**", "", ...argTable(command.args), "");
  }
  if (command.flags.length > 0) {
    lines.push("**Flags**", "", ...flagTable(command.flags), "");
  }

  lines.push("**Examples**", "");
  for (const example of command.examples) {
    lines.push(example.description, "", "```", example.command, "```", "");
  }
  return lines;
}

function argTable(args: readonly ArgSpec[]): readonly string[] {
  return table(
    ["Argument", "Required", "Description"],
    args.map((arg) => [`\`${arg.name}\``, arg.required ? "yes" : "no", arg.description]),
  );
}

function flagTable(flags: readonly FlagSpec[]): readonly string[] {
  return table(
    ["Flag", "Type", "Default", "Description"],
    flags.map((flag) => [
      `\`${flagUsage(flag)}\``,
      flag.repeated === true ? `${flag.type} (repeatable)` : flag.type,
      flag.default === undefined
        ? flag.type === "boolean"
          ? "`false`"
          : "—"
        : `\`${String(flag.default)}\``,
      flag.description,
    ]),
  );
}

function exitCodeTable(): readonly string[] {
  return table(
    ["Code", "Meaning"],
    EXIT_CODES.map((entry) => [`\`${String(entry.code)}\``, entry.meaning]),
  );
}

/**
 * A cell's own `|` would end the column early — `--from <user|agent>` would
 * render as two cells and Prettier would reflow the whole table around the
 * break. Escaping is the fix; the help renderer keeps the readable form.
 */
function escapeCell(cell: string): string {
  return cell.replace(/\|/g, "\\|");
}

/** Markdown table with padded columns, so the committed file is stable and readable. */
function table(
  headers: readonly string[],
  rows: readonly (readonly string[])[],
): readonly string[] {
  const escapedHeaders = headers.map(escapeCell);
  const escapedRows = rows.map((row) => row.map(escapeCell));
  const widths = escapedHeaders.map((header, column) =>
    Math.max(3, header.length, ...escapedRows.map((row) => (row[column] ?? "").length)),
  );
  const render = (cells: readonly string[]): string =>
    `| ${cells.map((cell, column) => cell.padEnd(widths[column] ?? cell.length)).join(" | ")} |`;

  return [
    render(escapedHeaders),
    `| ${widths.map((width) => "-".repeat(width)).join(" | ")} |`,
    ...escapedRows.map(render),
  ];
}

/** GitHub's heading-anchor rules: lowercase, drop punctuation, spaces become dashes. */
export function anchor(heading: string): string {
  return heading
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}
