import { OpenAPIHono } from "@hono/zod-openapi";
import { ALL_CONTRACT_ROUTES } from "./routes/index.js";

/**
 * Version stamped into the generated document. Bumped deliberately when the API
 * surface changes shape, not on every edit — it is the contract's version, not
 * the package's.
 */
export const CONTRACT_VERSION = "0.1.0";

export const BEARER_SECURITY_SCHEME = "bearerAuth";

/**
 * Builds the OpenAPI 3.1 document from the route definitions. This is the only
 * producer of `openapi.json`; the document is an artifact and is never hand-edited
 * (SPEC.md §9.3).
 */
export function buildOpenApiDocument(): ReturnType<OpenAPIHono["getOpenAPI31Document"]> {
  const app = new OpenAPIHono();

  app.openAPIRegistry.registerComponent("securitySchemes", BEARER_SECURITY_SCHEME, {
    type: "http",
    scheme: "bearer",
    description:
      "The workspace bearer token generated by `corpus init` and stored in `.corpus/config.json` (SPEC.md §2.1).",
  });

  for (const route of ALL_CONTRACT_ROUTES) {
    app.openAPIRegistry.registerPath(route);
  }

  return app.getOpenAPI31Document({
    openapi: "3.1.0",
    info: {
      title: "Corpus API",
      version: CONTRACT_VERSION,
      description:
        "The HTTP surface of a Corpus workspace server. Generated from the `@hono/zod-openapi` route " +
        "definitions in `packages/contract` — regenerate with `npm run generate -w packages/contract` " +
        "rather than editing this document. Plugin routes mount under `/api/x/<plugin>/...` and are " +
        "discovered at runtime, so they are deliberately absent here (SPEC.md §10).",
    },
    servers: [
      { url: "http://127.0.0.1:8765", description: "Default workspace server (SPEC.md §3)." },
    ],
    security: [{ [BEARER_SECURITY_SCHEME]: [] }],
    tags: [
      { name: "health", description: "Liveness and readiness." },
      { name: "docs", description: "The document collection and individual documents." },
      { name: "threads", description: "Threads and their turns." },
      { name: "queue", description: "The agent-side event queue." },
      { name: "events", description: "The SSE invalidation stream." },
    ],
  });
}
