import { OpenAPIHono } from "@hono/zod-openapi";
import { ALL_CONTRACT_ROUTES } from "./routes/index.js";

/**
 * Version stamped into the generated document. Bumped deliberately when the API
 * surface changes shape, not on every edit — it is the contract's version, not
 * the package's.
 */
export const CONTRACT_VERSION = "0.1.0";

export const BEARER_SECURITY_SCHEME = "bearerAuth";

/**
 * Builds the OpenAPI 3.1 document from the route definitions. This is the only
 * producer of `openapi.json`; the document is an artifact and is never hand-edited
 * (SPEC.md §9.3).
 */
export function buildOpenApiDocument(): ReturnType<OpenAPIHono["getOpenAPI31Document"]> {
  const app = new OpenAPIHono();

  app.openAPIRegistry.registerComponent("securitySchemes", BEARER_SECURITY_SCHEME, {
    type: "http",
    scheme: "bearer",
    description:
      "The workspace bearer token generated by `corpus init` and stored in `.corpus/config.json` (SPEC.md §2.1).",
  });

  for (const route of ALL_CONTRACT_ROUTES) {
    app.openAPIRegistry.registerPath(route);
  }

  return app.getOpenAPI31Document({
    openapi: "3.1.0",
    info: {
      title: "Corpus API",
      version: CONTRACT_VERSION,
      description:
        "The HTTP surface of a Corpus workspace server. Generated from the `@hono/zod-openapi` route " +
        "definitions in `packages/contract` — regenerate with `npm run generate -w packages/contract` " +
        "rather than editing this document. The server also serves this document at " +
        "`GET /api/openapi.json`, which is server-local introspection rather than client-facing " +
        "API and is therefore not declared here — no typed client method exists for it.",
    },
    servers: [
      { url: "http://127.0.0.1:8765", description: "Default workspace server (SPEC.md §3)." },
    ],
    security: [{ [BEARER_SECURITY_SCHEME]: [] }],
    tags: [
      { name: "health", description: "Liveness and readiness." },
      { name: "docs", description: "The document collection and individual documents." },
      {
        name: "search",
        description:
          "Retrieval: ranked search and related-document expansion (SPEC.md §7). Frugal by " +
          "contract — addresses and single lines, never bodies.",
      },
      { name: "tree", description: "The `data/docs/` folder hierarchy." },
      { name: "capture", description: "The composer's Capture action." },
      { name: "threads", description: "Threads and their turns." },
      { name: "queue", description: "The agent-side event queue." },
      { name: "jobs", description: "Job rows and their log streams — the console feed." },
      { name: "db", description: "Projection maintenance: rebuild and drift check." },
      { name: "check", description: "The corpus validator behind `corpus doc check`." },
      {
        name: "index",
        description:
          "The semantic index behind retrieval's second half (SPEC.md §9.1): its health, and the " +
          "rebuild that re-queues it. Derived runtime state only — no files, no commits.",
      },
      {
        name: "skills",
        description: "Skills as documents: genesis, the one write no document route can express.",
      },
      {
        name: "upgrade",
        description:
          "On-demand self-upgrade (SPEC.md §2.4): the check that reaches GitHub only when asked, " +
          "and the trigger that spawns the detached CLI upgrade. Nothing here runs in the " +
          "background, and nothing phones home.",
      },
      { name: "events", description: "The SSE invalidation stream." },
      { name: "attachments", description: "Attachment bytes." },
    ],
  });
}
